---
##########################
# versions

manager_version: latest
openstack_version: yoga

##########################
# celery

enable_celery: true
osism_api_host: "{{ hostvars[inventory_hostname]['ansible_' + internal_interface]['ipv4']['address'] }}"

##########################
# ara

enable_ara: true
ara_server_database_type: sqlite3
ara_server_host: "{{ hostvars[inventory_hostname]['ansible_' + internal_interface]['ipv4']['address'] }}"

##########################
# netbox

enable_netbox: false

##########################
# configuration

configuration_directory: /opt/configuration

configuration_type: git
configuration_git_version: main
configuration_git_host: github.com
configuration_git_port: 443
configuration_git_repository: osism/cloud-in-a-box.git
configuration_git_protocol: https
