---
##########################################################
# network

network_internal_interface: vlan100
network_mgmt_interface: eno1
network_workload_interface: eno2

network_type: netplan

network_ethernets:
  alleths:
    match:
      name: en*
    dhcp4: true
    optional: true

  eno1:
    dhcp4: true

network_vlans:
  vlan100:
    id: 100
    link: "{{ network_mgmt_interface }}"
    addresses:
      - "192.168.16.{{ node_id }}/24"
