---
##########################################################
# docker

docker_registry: quay.io

##########################################################
# loadbalancer

kolla_internal_vip_address: 192.168.16.254
kolla_internal_fqdn: api.cloud-in-a-box.osism.xyz

##########################################################
# openstack

# enable services
enable_cinder: "yes"
enable_cinder_backup: "yes"

enable_grafana: "yes"
enable_iscsid: "yes"
enable_prometheus: "yes"
enable_redis: "yes"
enable_tgtd: "yes"

# generic

openstack_service_workers: 2
openstack_logging_debug: "True"

# elasticsearch
es_heap_size: "1g"

enable_elasticsearch_curator: "yes"

elasticsearch_curator_soft_retention_period_days: 1
elasticsearch_curator_hard_retention_period_days: 1

# mariadb
enable_mariabackup: "yes"

# horizon
horizon_backend_database: "yes"

# keystone
keystone_token_provider: "fernet"

# libvirt
# NOTE: Doesn't work yet with our setup
libvirt_enable_sasl: "no"

# cinder
enable_iscsid_for_cinder: "yes"

# neutron
neutron_plugin_agent: ovn

enable_neutron_qos: "yes"

# NOTE: Disable the debugging logs for Libvirt as Libvirt writes a lot of logs
#       that are not of interest.
nova_libvirt_logging_debug: "no"

# nova
nova_console: novnc

# octavia
octavia_network_type: tenant

# designate
designate_ns_record: openstack.cloud-in-a-box.osism.xyz

##########################################################
# external ceph

enable_ceph: "no"

##########################################################
# other
